New folder/BookSiteWeb/Controllers/NavController.cs
using BookSiteWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookSiteWeb.Controllers
{
    public class NavController : Controller
    {
        private ApplicationDbContext repository = new ApplicationDbContext();
                
        public PartialViewResult Menu(string genre = null)
        {
            ViewBag.SelectedGenre = genre;

            IEnumerable<string> genres = repository.Newses
                .Select(book => book.Genre.Value.ToString())
                .Distinct()
                .OrderBy(x => x);
            
            return PartialView("FlexMenu",genres);
        }
    }
}

New folder/BookSiteWeb/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-2.2.0.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <title></title>
</head>
<body>
    <div>
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>

New folder/BookSiteWeb/Views/Shared/_BookSummary.cshtml
@model BookSiteWeb.Models.News

<div class="well">
    <div class="row">
        <div class="col-xs-9">
            <h3>
                <strong>@Html.ActionLink(@Model.Name, "Details", new { id = Model.NewsId })</strong>
            </h3>
            <br />
            <img src="@Html.Raw(Model.ImageURL)" width="500" />
        </div>
    </div>
    <br />
    <span class="lead">@Model.Description</span>
    <h5>
        Тeги:
        @foreach (var news in Model.Tags)
        {
            <b>
                @Html.ActionLink(news.TagName, "IndexTags", new { id = news.TagId })
            </b>
        }
    </h5>    
    <h4>
        @Html.ActionLink("Подробнее...", "Details", new { id = Model.NewsId })
    </h4>
</div>

New folder/BookSiteWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <link href='@Url.Content("~/Content/themes/base/all.css")' rel="stylesheet" type="text/css" />
    <script src='@Url.Content("~/Scripts/jquery-ui-1.12.1.min.js")' type="text/javascript"></script>
    <title></title>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ITNews - сайт новостей", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @Html.Partial("_LoginPartial")
            </div>           
        </div>
    </div>
    <br />
    <div class="visible-xs">
        @Html.Action("Menu", "Nav", new { horizontalNav = true })
    </div>
    <div class="row panel">
        <div id="genres" class="col-sm-3 hidden-xs">
            @Html.Action("Menu", "Nav")
        </div>
        <div class="col-xs-7 col-sm-7">
            @RenderBody()
        </div>  
        <div class="col-xs-2 col-sm-2" style="float:right">
            @Html.Partial("_TagSummary")
        </div>
    </div>
    <div class="container body-content">
        <footer>
            <p>&copy; @DateTime.Now.Year – ITNews - сайт новостей</p>
        </footer>
    </div>

    @Scripts.Render("~/scripts/jquery-3.3.1.js")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/scripts/jquery.unobtrusive-ajax.js")
    @RenderSection("scripts", required: false)
</body>
</html>

New folder/BookSiteWeb/Views/Shared/_NewsSummary.cshtml
@model BookSiteWeb.Models.Comment

<div class="well">
    <div class="row" style="width:25%;float:left">
        <div class="col-xs-9" style="width:25%;float:left">
            <h3>
                <strong>@Html.ActionLink(@Model.UserName, "Profile", new { userId = Model.UserId })</strong>
            </h3>
            <img src="@Html.Raw(Model.ImageURL)" height="100" />
        </div>
    </div>
    <div style="float:right">
        @Html.Partial("_DeliteComment", new BookSiteWeb.Models.Comment() { CommentId = Model.CommentId, NewsId = Model.NewsId, UserId = Model.UserId, ImageURL = Model.ImageURL, UserName = Model.UserName })
    </div>
    <br />
    <br />
    <br />
    <div class="lead" style="width:75%;float:left">@Model.Text</div>
    @{
        BookSiteWeb.Models.Comment ad = new BookSiteWeb.Models.Comment() { CommentId = Model.CommentId, NewsId = Model.NewsId, UserId = Model.UserId, ImageURL = Model.ImageURL, UserName = Model.UserName, CountLike = Model.CountLike };
    }
    <br />
    <br />
    <br />
    <br />
    <div>
        @Html.Partial("_TakeLike", ad)
    </div>
</div>

New folder/BookSiteWeb/Views/Shared/_RateBox.cshtml
@model BookSiteWeb.Models.Rating
<dd>
    <div>
        @using (Html.BeginForm("_TakeRate", "Home", FormMethod.Post, new { onsubmit = "return SubmitComment()" }))
        {
            @Html.AntiForgeryToken()
            <div class="form-horizontal">
                <div class="form-group">                    
                    <div class="col-md-7">
                        <div onmouseout="CRateSelected()">
                            <b style="width:35%;float:left">
                                <span class="starFade" id="Rate1" onclick="CRate(1)" onmouseover="CRateOver(1)" onmouseout="CRateOut(1)"></span><span class="starFade" id="Rate2" onclick="CRate(2)" onmouseover="CRateOver(2)" onmouseout="CRateOut(2)"></span><span class="starFade" id="Rate3" onclick="CRate(3)" onmouseover="CRateOver(3)" onmouseout="CRateOut(3)"></span><span class="starFade" id="Rate4" onclick="CRate(4)" onmouseover="CRateOver(4)" onmouseout="CRateOut(4)"></span><span class="starFade" id="Rate5" onclick="CRate(5)" onmouseover="CRateOver(5)" onmouseout="CRateOut(5)"></span>
                            </b>
                            <input type="hidden" name="NewsId" value="@Model.NewsId" />
                            <input type="hidden" name="Rating" id="Rating" value="0" />
                            <input type="submit" id="btnRegister" name="btnRegister" value="Добавить рейтинг" class="btn btn-warning" />
                        </div>
                    </div>
                    
                </div>
                        
            </div>
        }
    </div>
</dd>

<script>
    function SubmitComment() {
        if ($("#Rating").val() == "0") {
            alert("Please rate this service provider.");
            return false;
        }
        else {
            return true;
        }
    }

    function CRate(r) {
        $("#Rating").val(r);
        for (var i = 1; i <= r; i++) {
            $("#Rate" + i).attr('class', 'starGlow');
        }
        // unselect remaining
        for (var i = r + 1; i <= 5; i++) {
            $("#Rate" + i).attr('class', 'starFade');
        }
    }

    function CRateOver(r) {
        for (var i = 1; i <= r; i++) {
            $("#Rate" + i).attr('class', 'starGlow');
        }
    }

    function CRateOut(r) {
        for (var i = 1; i <= r; i++) {
            $("#Rate" + i).attr('class', 'starFade');
        }
    }

    function CRateSelected() {
        var setRating = $("#Rating").val();
        for (var i = 1; i <= setRating; i++) {
            $("#Rate" + i).attr('class', 'starGlow');
        }
    }
</script>

New folder/BookSiteWeb/Views/Shared/_TagSummary.cshtml
@using BookSiteWeb.Models

@{
 ApplicationDbContext repository = new ApplicationDbContext();
}

<div class="well">
    @foreach (var news in repository.Tags)
    {
        <h3>
            @Html.ActionLink(news.TagName, "IndexTags", new { id = news.TagId })
            <br />
        </h3>
    }

</div>